name: Release next

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to bump to [auto|major|minor|patch|semver]
        default: auto
        required: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  bump-version:
    name: Release next
    runs-on: ubuntu-latest

    if: github.event.ref == 'refs/heads/main'

    steps:
      - name: Checkout current commit
        uses: "actions/checkout@v4"
        with:
          token: ${{ secrets.COMMIT_TOKEN }}

      - name: Update changelog with release version
        env:
          GITHUB_EVENT: ${{ toJSON(github.event) }}
          GITHUB_TOKEN: ${{ github.token }}
          RELEASE_NEXT: ${{ github.event.inputs.version }}
        run: |
          .github/workflows/scripts/release.py --release-next "$RELEASE_NEXT" | tee -a "$GITHUB_ENV"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "info.md"
          commit_message: ${{ env.RELEASE_EMOJI }} Release version ${{ env.RELEASE_VERSION }}
